baseURL = "http://24sockproject.me/"
languageCode = "en-ca"
title = "The 24 Sock Project"
theme = "hugo-initio"
# publishDir = "docs"

[params]
    name = "The 24 Sock Project"
    description = "My goal to knit 24 socks (12 pairs) in 2018"
    email = "geoff@geoffholden.com"
    # phone = "+234 23 9873237"
    # address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    background = ""
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"

    showSubheader = false
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/page/about/"
    weight = 2
[[menu.main]]
    name = "rules"
    url = "/page/rules/"
    weight = 3

[params.disqus]
    site = "24-sock-project.disqus.com"

[params.sharethis]
    property = "5a2318501b1181001358773e"
    custom = false

# [params.google.analytics]
#     trackerID = "GA-000000000-0"

# [[params.social]]
#     title = "twitter"
#     url = "https://twitter.com/nickname"
#     icon = "fa-twitter-square"
#     footer = true
#     sharethis = true
#     network = "twitter"
[[params.social]]
    title = "instagram"
    url = "https://www.instagram.com/24sockproject"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""

[[params.social]]
    title = "email"
    url = "mailto:geoff@geoffholden.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"

[[params.social]]
    title = "ravelry"
    url = "https://www.ravelry.com/people/WifeMadeMeDoIt"
    icon = "fa-ravelry"
    footer = true
    sharethis = false
    network = ""

[[params.social]]
    title = "rss"
    url = "/post/index.xml"
    icon = "fa-rss"
    footer = true
    sharethis = false
    network = ""
